name: scripture
description: A text layout engine optimized for USFM Bible data, featuring custom paragraph formatting and word-level interactivity.
version: 0.2.1
repository: https://github.com/ethnosdev/scripture

environment:
  sdk: ^3.9.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - text
  - layout
  - bible
  - usfm
  - widget

screenshots:
  - description: 'Complex USFM Layout rendering poetry and footnotes'
    path: screenshots/usfm_layout.png